### ISSUE TITLE
How to mock AsyncListDifferDelegationAdapter

### ISSUE THREAD

**Issue by lsrom** [sockeqwe/AdapterDelegates#67]
Hi, I have class extending AsyncListDifferDelegationAdapter and want to write unit tests for it. Problem is that is fails with `java.lang.ExceptionInInitializerError`, `Method getMainLooper in android.os.Looper not mocked`.

How do I mock the async stuff so I can write unit tests? I'm using `com.nhaarman.mockitokotlin2`.

Stacktrace:
java.lang.ExceptionInInitializerError
	at com.hannesdorfmann.adapterdelegates4.AsyncListDifferDelegationAdapter.<init>(AsyncListDifferDelegationAdapter.java:60)
	at com.hannesdorfmann.adapterdelegates4.AsyncListDifferDelegationAdapter.<init>(AsyncListDifferDelegationAdapter.java:47)
	at com.netsuite.nsforandroid.core.collection.ui.view.RecyclerCollectionAdapter.<init>(RecyclerCollectionAdapter.kt:27)
	at com.netsuite.nsforandroid.core.collection.ui.view.RecyclerCollectionAdapter.<init>(RecyclerCollectionAdapter.kt:26)
	at com.netsuite.nsforandroid.core.collection.ui.view.RecyclerCollectionAdapter$Companion.invoke(RecyclerCollectionAdapter.kt:108)
	at com.netsuite.nsforandroid.core.collection.ui.view.RecyclerCollectionAdapterTest.<init>(RecyclerCollectionAdapterTest.kt:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by sockeqwe** [comment]
The problem is that it needs a `AsyncListDiffer`  which causes th problem you are describing. 

On the other hand, why would one mock a RecyclerView Adapter?

**Comment by lsrom** [comment]
My Adapter contains some custom logic that I would like to test. But since I can't mock the `AsyncListDiffer` and I'm not passing the `differConfig` I think I may need to reevaluate my architecture and pull this functionality out of the adapter for cleaner architecture and easier testing.

Thanks!

**Comment by sockeqwe** [comment]
That sounds like a much better strategy. Thanks.
