### ISSUE TITLE
[CRASH] adapterDelegateViewBinding's block crashing

### ISSUE THREAD

**Issue by jeantuffier** [sockeqwe/AdapterDelegates#93]
I'm experiencing a crash when using `adapterDelegateViewBinding`

The code I use :
```
val adapter = ListDelegationAdapter<List<ViewAllItem>>(
        comicAdapterDelegate()
    )

    private fun comicAdapterDelegate() =
        adapterDelegateViewBinding<ViewAllItem.Comic, ViewAllItem, ComicOverviewItemBinding>(
            viewBinding = { layoutInflater, root ->
                ComicOverviewItemBinding.inflate(
                    layoutInflater,
                    root,
                    false
                )
            }
        ) {
            binding.title.text = item.comic.title
            binding.subTitle.text = item.comic.dates[0].toString()
            binding.image.load(ImageUtils.formatImage(item.comic.thumbnail)) {
                crossfade(true)
                placeholder(R.drawable.placeholder)
            }
        }
...
binding?.recyclerView?.adapter = adapter.apply { items = emptyList() }
```

I update the items later once I fetch the content from an api :
```
adapter.items = adapter.items + state.items
adapter.notifyDataSetChanged()
```
This result in the following crash :
```
    java.lang.IllegalArgumentException: Item has not been set yet. That is an internal issue. Please report at https://github.com/sockeqwe/AdapterDelegates
        at com.hannesdorfmann.adapterdelegates4.dsl.AdapterDelegateViewBindingViewHolder.getItem(ViewBindingListAdapterDelegateDsl.kt:132)
        at com.jeantuffier.inorder.inorder_android.screen.viewall.ViewAllViewModel$comicAdapterDelegate$2.invoke(ViewAllViewModel.kt:75)
        at com.jeantuffier.inorder.inorder_android.screen.viewall.ViewAllViewModel$comicAdapterDelegate$2.invoke(ViewAllViewModel.kt:22)
        at com.hannesdorfmann.adapterdelegates4.dsl.DslViewBindingListAdapterDelegate.onCreateViewHolder(ViewBindingListAdapterDelegateDsl.kt:63)
        at com.hannesdorfmann.adapterdelegates4.dsl.DslViewBindingListAdapterDelegate.onCreateViewHolder(ViewBindingListAdapterDelegateDsl.kt:47)
        at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onCreateViewHolder(AdapterDelegatesManager.java:267)
        at com.hannesdorfmann.adapterdelegates4.AbsDelegationAdapter.onCreateViewHolder(AbsDelegationAdapter.java:88)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1695)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
2020-08-05 21:35:13.318 30468-30468/com.jeantuffier.inorder.inorder_android E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1062)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
2020-08-05 21:35:13.348 30468-30468/com.jeantuffier.inorder.inorder_android I/Process: Sending signal. PID: 30468 SIG: 9
```

If I comment out :
```
binding.title.text = item.comic.title
            binding.subTitle.text = item.comic.dates[0].toString()
            binding.image.load(ImageUtils.formatImage(item.comic.thumbnail)) {
                crossfade(true)
                placeholder(R.drawable.placeholder)
            }
```
Then I do not get any crash

**Comment by sockeqwe** [comment]
Hello,
Thanks for reporting.
Is there a way how to reproduce this or in best case, can you provide a sample that reproduce this?

Also does it happen on the first time this item is shown or after you change your adapters dataset? Do you call notifydatasetChanges() or do you use DiffUtils?

**Comment by jeantuffier** [comment]
I wrote my own adapters in the meantime so I don't have the code that generate that particular issue.
From memory, I was following this steps : 
1. create ListDelegationAdapter with empty list of items
2. set the items after fetching them from api
3. call  `notifydatasetChanges()`

**Comment by IgorRAzumov** [comment]
1) create  AsyncListDifferDelegationAdapter( AsyncListDifferDelegationAdapter(@NonNull DiffUtil.ItemCallback<T> diffCallback,
@NonNull AdapterDelegatesManager<List<T>> delegatesManager) )

setItems
3)

**Comment by IgorRAzumov** [comment]
1 -without viewBinding                                                                                                                                                                      
2 -create  AsyncListDifferDelegationAdapter with empty list of items
3 -setItems
4- firstDelegate where calling bind{} - 
![image](https://user-images.githubusercontent.com/26173729/90221106-d6522100-de09-11ea-861d-61dc8366164d.png)

**Comment by nassdk** [comment]
Faced with same issue.
`java.lang.IllegalArgumentException: Item has not been set yet. That is an internal issue. Please report at https://github.com/sockeqwe/AdapterDelegates
        at com.hannesdorfmann.adapterdelegates4.dsl.AdapterDelegateViewBindingViewHolder.getItem(ViewBindingListAdapterDelegateDsl.kt:132)
        at com.flow.kafedra.presentation.screens.purchases.PurchasesFragment$ordersDelegate$2.invoke(PurchasesFragment.kt:161)
        at com.flow.kafedra.presentation.screens.purchases.PurchasesFragment$ordersDelegate$2.invoke(PurchasesFragment.kt:31)
        at com.hannesdorfmann.adapterdelegates4.dsl.DslViewBindingListAdapterDelegate.onCreateViewHolder(ViewBindingListAdapterDelegateDsl.kt:63)
        at com.hannesdorfmann.adapterdelegates4.dsl.DslViewBindingListAdapterDelegate.onCreateViewHolder(ViewBindingListAdapterDelegateDsl.kt:47)
        at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onCreateViewHolder(AdapterDelegatesManager.java:267)
        at com.hannesdorfmann.adapterdelegates4.AbsDelegationAdapter.onCreateViewHolder(AbsDelegationAdapter.java:88)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:27131)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:763)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:426)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:105)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:247)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:117)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1532)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1607)
        at android.view.View.measure(View.java:27131)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27131)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27131)`

**Comment by acolombo25** [comment]
You're not calling the bind block. See the [how to use it](https://github.com/sockeqwe/AdapterDelegates#how-to-use-it) section of the docs and more importantly the docs of [adapterDelegateViewBinding(...)](https://github.com/sockeqwe/AdapterDelegates/blob/5092dbf64f35843b02fbf46ab3ac03a7c55496ea/kotlin-dsl-viewbinding/src/main/java/com/hannesdorfmann/adapterdelegates4/dsl/ViewBindingListAdapterDelegateDsl.kt)

Instead of this:
```kotlin
private fun comicAdapterDelegate() = adapterDelegateViewBinding<ViewAllItem.Comic, ViewAllItem, ComicOverviewItemBinding>(
      viewBinding = { layoutInflater, root -> ComicOverviewItemBinding.inflate(layoutInflater, root, false) }
) {
    binding.title.text = item.comic.title
    binding.subTitle.text = item.comic.dates[0].toString()
    binding.image.load(ImageUtils.formatImage(item.comic.thumbnail)) {
        crossfade(true)
        placeholder(R.drawable.placeholder)
    }
}
```
        
You should write this:
```kotlin
private fun comicAdapterDelegate() = adapterDelegateViewBinding<ViewAllItem.Comic, ViewAllItem, ComicOverviewItemBinding>(
      viewBinding = { layoutInflater, root -> ComicOverviewItemBinding.inflate(layoutInflater, root, false) }
) {
    bind {
        binding.title.text = item.comic.title
        binding.subTitle.text = item.comic.dates[0].toString()
        binding.image.load(ImageUtils.formatImage(item.comic.thumbnail)) {
            crossfade(true)
            placeholder(R.drawable.placeholder)
        }
    }
}
```

tbh I agree that this api is a bit cumbersome to use and a bit unsafe
